name: PR Rule Check

on:
  pull_request:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: github/copilot-actions/review@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          rules: .github/copilot-instructions.md